apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: mongodb
spec:
  selector:
    matchLabels:
      app: mongo
  serviceName: mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      volumes:
        - name: mongo-volume1
          persistentVolumeClaim:
            claimName: mongo-volume
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongo
        image: mongo
        command: 
        - mongod 
        - --bind_ip_all
        - --replSet
        - rs0
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-volume1
          mountPath: /data/db
