apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app-flask
  name: app-flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-flask
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app-flask
    spec:
      containers:
      - image: app-flask-user1/dtr.example.com:v1  
        env:
        - name: mongo_user
          value: "mongodbadmin"
        - name: mongo_password
          value: "1qazxsw2"
        - name: PORT
          value: "5000"
        name: kubernetes
        resources: {}
status: {}
