apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app_flask
  name: app_flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app_flask
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app_flask
    spec:
      containers:
      - image: app-flask-user1/dtr.example.com:v1
        name: kubernetes
        resources: {}
status: {}
