apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: app_flask
  name: app_flask-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: app_flask
  type: LoadBalancer
status:
  loadBalancer: {}
